learning/basic/urls.py
from django.conf.urls import url
from basic import views
app_name='zico'

urlpatterns=[
     url(r'^relative/',views.relative,name='relative'),
     url(r'^other/',views.other,name='other'),
     url(r'^$',views.home,name='home'),
]

learning/learning/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from basic import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hopa/',include('basic.urls')),
]

learning/basic/models.py
from django.db import models

# Create your models here.

learning/basic/views.py
from django.shortcuts import render

def home(request):
    dict={'key':'hello world','number':100}

    return render (request,'basico/home.html',dict)
def other (request):
    return render (request,'basico/other.html')
def relative(request):
    return render (request,'basico/relative.html')

# Create your views here.

learning/templates/basico/home.html
<!DOCTYPE html>
{% load my_extras %}

  <head>
    <meta charset="utf-8">
    <title>home page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"

  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class ='nav navbar-nav'>
          <li><a class='navbar-link' href="{% url 'zico:other' %}">go to other</a></li>
          <li><a class='navbar-link' href="{% url 'zico:relative' %}">go to relative</a></li>
        </ul>
      </div>
    </nav>
    {% block body_block %}
    <h1>Welcome to home</h1>
    <h1>{{ key |cu:'hello'}}</h1>
    <h1>{{number| add:'66'}}</h1>
    {% endblock %}
  </body>
</html>

learning/templates/basico/other.html
<!DOCTYPE html>
{% extends 'basico/home.html' %}
{% block body_block %}
<h1>Welcome to other</h1>
{% endblock %}

learning/templates/basico/relative.html
<!DOCTYPE html>
{% extends 'basico/home.html' %}
{% block body_block %}
<h1>Welcome to relative</h1>
<a href="{% url 'zico:home' %}">go home</a>

{% endblock %}